# -*- coding: utf-8 -*-
"""5week_hw

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkucVmPbLZA6LwFtAfwb-vwFh-U9Xd3p
"""

# 함수 정의
def add_numbers(a, b):
    """두 숫자를 더하는 함수"""
    return a + b

# 함수 실행 예시
if __name__ == "__main__":
    result = add_numbers(3, 5)
    print(f"결과: {result}")
    
# branch03에서 추가됨